### ISSUE TITLE
Running transformers_tutorial.py

### ISSUE THREAD

**Issue by n8stringham** [mikeizbicki/cmc-csci181#40]
I've copied over the transformers_tutorial.py file to my computer, but can't seem to get it to run. After commenting out the first `crash` on line 38 and running I get the following error message:

```Traceback (most recent call last):
  File "transformers_tutorial.py", line 50, in <module>
    return_tensors = 'pt',
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 786, in encode_plus
    first_ids = get_input_ids(text)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 778, in get_input_ids
    return self.convert_tokens_to_ids(self.tokenize(text, **kwargs))
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 649, in tokenize
    tokenized_text = split_on_tokens(added_tokens, text)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 646, in split_on_tokens
    else [token] for token in tokenized_text), [])
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 646, in <genexpr>
    else [token] for token in tokenized_text), [])
TypeError: _tokenize() got an unexpected keyword argument 'pad_to_max_length' 
```
Looks like it has to do with the parameters for the `tokenizer.encode_plus()` function, but I'm not sure how to fix this error.

**Comment by mikeizbicki** [comment]
My guess is that you have an older version of transformers installed that uses a different interface for that function.  Here's the version info I used to run the code:
```
$ python3
>>> import transformers
>>> import torch
>>> import tensorboard
>>> transformers.__version__
'2.8.0'
>>> torch.__version__
'1.5.0'
>>> tensorboard.__version__
'2.2.1'
```

**Comment by n8stringham** [comment]
Yep, I just had an older version of transformers. Thanks!

**Comment by sarahbashir** [comment]
I also can't get the file to run.

These are the error messages I get when I try to pip3 install (my pip install is always with Python 2 for some reason):

```Building wheels for collected packages: tokenizers
  Building wheel for tokenizers (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/2n/207m7qnj6k39pm05nf7q_bf00000gn/T/tmpcm91db3p
       cwd: /private/var/folders/2n/207m7qnj6k39pm05nf7q_bf00000gn/T/pip-install-ufkwk8kb/tokenizers
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/tokenizers
  copying tokenizers/__init__.py -> build/lib/tokenizers
  creating build/lib/tokenizers/models
  copying tokenizers/models/__init__.py -> build/lib/tokenizers/models
  creating build/lib/tokenizers/decoders
  copying tokenizers/decoders/__init__.py -> build/lib/tokenizers/decoders
  creating build/lib/tokenizers/normalizers
  copying tokenizers/normalizers/__init__.py -> build/lib/tokenizers/normalizers
  creating build/lib/tokenizers/pre_tokenizers
  copying tokenizers/pre_tokenizers/__init__.py -> build/lib/tokenizers/pre_tokenizers
  creating build/lib/tokenizers/processors
  copying tokenizers/processors/__init__.py -> build/lib/tokenizers/processors
  creating build/lib/tokenizers/trainers
  copying tokenizers/trainers/__init__.py -> build/lib/tokenizers/trainers
  creating build/lib/tokenizers/implementations
  copying tokenizers/implementations/byte_level_bpe.py -> build/lib/tokenizers/implementations
  copying tokenizers/implementations/sentencepiece_bpe.py -> build/lib/tokenizers/implementations
  copying tokenizers/implementations/base_tokenizer.py -> build/lib/tokenizers/implementations
  copying tokenizers/implementations/__init__.py -> build/lib/tokenizers/implementations
  copying tokenizers/implementations/char_level_bpe.py -> build/lib/tokenizers/implementations
  copying tokenizers/implementations/bert_wordpiece.py -> build/lib/tokenizers/implementations
  copying tokenizers/__init__.pyi -> build/lib/tokenizers
  copying tokenizers/models/__init__.pyi -> build/lib/tokenizers/models
  copying tokenizers/decoders/__init__.pyi -> build/lib/tokenizers/decoders
  copying tokenizers/normalizers/__init__.pyi -> build/lib/tokenizers/normalizers
  copying tokenizers/pre_tokenizers/__init__.pyi -> build/lib/tokenizers/pre_tokenizers
  copying tokenizers/processors/__init__.pyi -> build/lib/tokenizers/processors
  copying tokenizers/trainers/__init__.pyi -> build/lib/tokenizers/trainers
  running build_ext
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for tokenizers
  Running setup.py clean for tokenizers
Failed to build tokenizers
Building wheels for collected packages: sacremoses, regex
  Building wheel for sacremoses (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp37-none-any.whl size=893261 sha256=271632254533e8498bf1bd8deaf1d4fc013c8681ef4b20e246e7978bc8b7f24b
  Stored in directory: /Users/sarahbashir/Library/Caches/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
  Building wheel for regex (setup.py) ... done
  Created wheel for regex: filename=regex-2020.4.4-cp37-cp37m-macosx_10_14_x86_64.whl size=285910 sha256=e90f4d18b64acc7bb254f312089fc639ac7d9160b388788591be2b377f7b0779
  Stored in directory: /Users/sarahbashir/Library/Caches/pip/wheels/e6/9b/ae/2972da29cc7759b71dee015813b7c6931917d6a51e64ed5e79
Successfully built sacremoses regex
ERROR: Could not build wheels for tokenizers which use PEP 517 and cannot be installed directly
```

When I run transformers_tutorial.py I get ```File "transformers_tutorial.py", line 11, in <module>
    import transformers
ModuleNotFoundError: No module named 'transformers'```
